name: glmhmm
channels:
  # - defaults
  - conda-forge
dependencies:
  - pip==22.3.1
  - python==3.10.9
  - pip:
    - setuptools==68.2.2 # necessary for ibllib installation
    - wheel==0.41.2 # necessary for ibllib installation
    - opencv-python==4.8.1.78 # necessary for ibllib installation
    - ibllib==2.*
    - matplotlib==3.*
    - numba==0.58.0
    - numpy==1.*
    - pandas==2.*
    - pytest==6.2.5
    - scikit-learn==1.*
    - scipy==1.*
    - seaborn==0.13.0
    - wget==3.2
